
version: '3.8'
services:
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: citebook_backend
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    expose: 
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql
      - ./data preparation:/var/lib/mysql-files
      
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
        PMA_ARBITRARY: 1
      
  backend:
    restart: always
    build:
      context: ./citebook_backend
      dockerfile: Dockerfile
    volumes:
      - ./citebook_backend/:/var/www/html
    depends_on:
      - db
    ports:
      - 8000:8000
  
  frontend:
    restart: always
    build:
      context: ./citebook_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./citebook_frontend/:/var/www/
    depends_on:
      - backend

volumes:
  db_data:
